### ISSUE TITLE
[WIP]Fix the error "Field “xxx” does not exist." when data is imported from Kafka to Nebula Graph via Nebula Exchange 

### ISSUE THREAD

**Issue by jamieliu1023** [vesoft-inc/nebula-exchange#8]
The bug was reported by a user on the Chinese forum: https://discuss.nebula-graph.com.cn/t/topic/2623/

For those who cannot understand Chinese well, please refer to the title of the issue for a basic background. The reason why the error occurs is that Nebula Exchange is not able to parse the "value" field of the data in Kafka. 

Committer @guojun85 is working on this now. Thanks for his contribution in advance!

**Comment by sworduo** [comment]
I am sorry that I can not reply in this pr vesoft-inc/nebula-spark-utils#157. Sorry about my poor English. I am not very sure what "can we just modify the StreamingReader to parse the kafka's value to DataFrame" means. Does it mean we just modify the input logic and try to transform the Kafka data to DataFrame while maintain the process logic as before, i.e. get DataFrame from Kafka source and parse it in vertice/edgeProcessor separately? If we want to implement it, the first question is how to switch vertices/edgeProcessor.
For Kafka source, according to the code, we can not switch to another tag/edge once a tagconfig is chosen. In this case, we can only parse one tag defined in config to nebula.
Let's assuming that the number of tag and edge defined in config is N. One possible solution is that we create N sparkContext and N Kafka streaming reader. With the help of Muti-thread, each tag/edge is processed in one thread with one Kafka consumer separately. However, I don't think it's a good idea. Assuming that partition is P, in this case, there is N * P partition and N * P nebula-writer. Maybe it will throw a socket exception.
In addition, we find a bug in the pr. In the last version, it is only supported string type vid/source/target while the int type vid/source/target maybe throw exception. This is because we call jsonObj.getString() default for vid/source/target. However, for int type vid/source/target, it should call jsonObj.getLong(). It can be easily fixed in the KakfaProcessor.scala everywhere the getAndCheckVID is called.

> That‘s reasonable, Iooking forward to your pr ~

**Comment by Nicole00** [comment]
So sorry for reply late. 
It is look good to me, just two questions:
1. can we process the kafka's data all in the Reader stage? The architecture commands the DataFrame that has entered VertexProcess/EdgeProcess does not need more process logic.
2. that's a great idea to check the configuration at the beginning. However, if users' tag config oder is `csv,kafka`, then it is not allowed? In fact, the datasource `csv` and `kafka` can all be imported successfully.  Maybe we need to ensure that there's no more other tag/edge config after `kafka`?

**Comment by sworduo** [comment]
1. I am not very sure. Since the json string is recorded in the value field of Kafka, we have to get Kafka data before parsing json. Maybe we can map the data in reader. But I have no idea whether it can work. If not, we can parse json in the tag/edgeprocessor.
2. Yes, you're right. We just need to ensure that there is no config after Kafka, which will be detected at the beginning.

**Comment by Nicole00** [comment]
In the Reader process, we can use the config `fields` to parse kafka's json value, just like:

assume flieds config is:[id,name,age]   (all fields must exist in kafka's value data) 

```
val df = session.readStream
      .format("kafka")
      .option("kafka.bootstrap.servers", kafkaConfig.server)
      .option("subscribe", kafkaConfig.topic)
      .load()
df.select(get_json_object($"value", "$.id").alias("id"), get_json_object($"value", "$.name").alias("name"), get_json_object($"value", "$.age").alias("age")).show()
```

Then we get the needed DataFrame from kafka, and other process keep the same with current logic.

**Comment by sworduo** [comment]
I get your point. I will try it like df.select(value).map(v => parseJson)

**Comment by Nicole00** [comment]
https://github.com/vesoft-inc/nebula-exchange/pull/29 resolved it.
